# Generated by Django 5.2.10 on 2026-02-01 01:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanJob",
            fields=[
                (
                    "job_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("mode", models.CharField(default="fast", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("pages_scanned", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LLMInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "target_url",
                    models.URLField(default="https://example.com", max_length=500),
                ),
                ("query_text", models.TextField(default="")),
                (
                    "engine",
                    models.CharField(
                        help_text="e.g. openai, anthropic, gemini", max_length=50
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="Specific model used e.g. gpt-4o",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "prompt_text",
                    models.TextField(help_text="The actual prompt sent to the LLM"),
                ),
                (
                    "response_text",
                    models.TextField(help_text="The raw response received"),
                ),
                ("tokens_input", models.IntegerField(default=0)),
                ("tokens_output", models.IntegerField(default=0)),
                ("cost_usd", models.FloatField(default=0.0)),
                ("latency_ms", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra context like job_id, user_id, etc.",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["engine", "timestamp"],
                        name="core_llmint_engine_3a1223_idx",
                    ),
                    models.Index(
                        fields=["success"], name="core_llmint_success_cdd8d9_idx"
                    ),
                ],
            },
        ),
    ]
