# Generated by Django 5.2.10 on 2026-02-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_appuser_product_llminteraction_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="default_mode",
            field=models.CharField(
                choices=[("fast", "Fast"), ("rendered", "Rendered")],
                default="fast",
                max_length=20,
            ),
        ),
    ]
