# Generated by Django 5.2.10 on 2026-02-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_product_default_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="business_bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="gender_preference",
            field=models.CharField(default="All", max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="is_bio_ai_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="target_audience_age",
            field=models.CharField(default="All", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="target_region",
            field=models.CharField(default="Global", max_length=100),
        ),
    ]
