# Generated by Django 5.2.10 on 2026-02-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_product_business_bio_product_gender_preference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="competitors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of top 5 competitors",
                null=True,
            ),
        ),
    ]
