# Generated by Django 5.2.10 on 2026-02-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_product_competitors"),
    ]

    operations = [
        migrations.AddField(
            model_name="llminteraction",
            name="analysis_data",
            field=models.JSONField(
                blank=True,
                help_text="Structured analysis of the response (SoV, Sentiment, Rank, etc.)",
                null=True,
            ),
        ),
    ]
