# Generated by Django 5.2.10 on 2026-02-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_llminteraction_analysis_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="suggested_queries",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Persisted strategic questions",
                null=True,
            ),
        ),
    ]
