# Generated by Django 5.2.10 on 2026-02-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_product_suggested_queries"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanjob",
            name="ai_readiness_score",
            field=models.FloatField(
                blank=True, help_text="Calculated readiness score 0-100", null=True
            ),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="readiness_summary",
            field=models.JSONField(
                blank=True, help_text="Breakdown of readiness score weights", null=True
            ),
        ),
    ]
